### ISSUE TITLE
Can DeepFrag add several fragments at one time?

### ISSUE THREAD

**Issue by Serious-Huang** [durrantlab/deepfrag#2]
Hi, thanks for the nice paper! I have used the web application before. And I wonder can DeepFrag add several fragments at one time?
![image](https://github.com/durrantlab/deepfrag/assets/129483484/a6edfa74-6f72-433d-80f3-cb7118696387)

**Comment by jacobdurrant** [comment]
Thanks for your interest in DeepFrag! The program is designed to add only one fragment at a time. You can certainly take the output of one DeepFrag run and feed it into a new run, though, if you want to add multiple fragments in serial. Hope this helps! ~Jacob

**Comment by Serious-Huang** [comment]
I see. Thank you!
